# Generated by Django 2.2.6 on 2019-12-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkyObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('type', models.IntegerField(choices=[(0, 'ozvezdje'), (1, 'zvezda')], verbose_name='Type')),
            ],
        ),
    ]
